# Generated by Django 5.0 on 2024-02-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_category_en_us_category_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type_ru',
        ),
    ]
